# Generated by Django 4.0.5 on 2023-08-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_fivegsttoken_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IperfStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.JSONField()),
                ('start_timestamp', models.DateTimeField()),
            ],
        ),
    ]
