# Generated by Django 4.0.5 on 2023-08-04 11:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_iperfstatistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='iperfstatistics',
            name='start_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 4, 11, 53, 38, 625780, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
