services:
  postgres:
    image: postgres:${POSTGRES_VERSION-14.4}
    container_name: postgres
    environment:
      POSTGRES_DB: ${DB_NAME-5gst_db_name}
      POSTGRES_USER: ${DB_USER-5gst_db_user}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT-5432}:5432"
    healthcheck: 
        test: [ "CMD","pg_isready", "-q", "-d", "${DB_NAME-5gst_db_name}", "-U", "${DB_USER-5gst_db_user}" ]
        interval: 5s
        timeout: 5s
        retries: 100


      
  balancer:
    image: 5gst/speedtest-balancer:${BALANCER_VERSION-latest}
    container_name: balancer
    depends_on:
        postgres:
            condition: service_healthy
    healthcheck:
        test: ["CMD", "curl","-f", "http://${SERVER_HOST}:5555/5gst/iperf_load_balancer/0.1.0/ping/"]
        interval: 5s
        timeout: 5s
        retries: 100
    entrypoint: ["/bin/bash", "-c", "sleep 20 && pipenv run python manage.py migrate && pipenv run gunicorn balancer.wsgi -b :8080"]
    environment:
      - SERVICE_URL_SCHEME=${SERVICE_URL_SCHEME-https}
      - SECRET_KEY=${BALANCER_SECRET_KEY}
      - DEBUG=${DEBUG-False}
      - ALLOWED_HOSTS=127.0.0.1,${SERVER_HOST}
      - DB_NAME=${DB_NAME-5gst_db_name}
      - DB_USER=${DB_USER-5gst_db_user}
      - DB_PASSWORD=${DB_PASS}
      - DB_HOST=${SERVER_HOST}
      - DB_PORT=${DB_PORT-5432}
    ports:
      - "${BALANCER_PORT-5555}:8080"
      


  service: 
    image: 5gst/speedtest-service:${SERVICE_VERSION-latest}
    container_name: serv1
    depends_on:
        balancer:
            condition: service_healthy
    environment:
      -  ALLOWED_HOSTS=127.0.0.1,${SERVER_HOST}
      -  BALANCER_ADDRESS=${SERVER_HOST}:${BALANCER_PORT-5555}
      -  BALANCER_BASE_URL=/5gst/iperf_load_balancer/0.1.0
      -  BALANCER_REGISTRATION_INTERVAL_SECONDS=${BALANCER_REGISTRATION_INTERVAL_SECONDS-15.0}
      -  IPERF_MEASUREMENT_MAX_TIME_SECONDS=${IPERF_MEASUREMENT_MAX_TIME_SECONDS-15.0}
      -  SESSION_MAX_IDLE_TIME_SECONDS=${SESSION_MAX_IDLE_TIME_SECONDS-15.0}
      -  DEBUG=${DEBUG-False}
      -  IPERF_PORT=${IPERF_PORT-5005}
      -  SECRET_KEY=${SERVICE_SECRET_KEY}
      -  SERVICE_IP_ADDRESS=${SERVER_HOST}
      -  SERVICE_PORT=${SERVICE_PORT-5004}
    ports:
      -  "${SERVICE_PORT-5004}:5000"
      -  "${IPERF_PORT-5005}:${IPERF_PORT-5005}"
      -  "${IPERF_PORT-5005}:${IPERF_PORT-5005}/udp"
