# coding: utf-8

"""
    Service API

    Speedtest iperf service  # noqa: E501

    OpenAPI spec version: 0.1.0
    Contact: dev@5gst.ru
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from service_api.configuration import Configuration


class IperfSpeedProbes(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'probes': 'list[int]'
    }

    attribute_map = {
        'probes': 'probes'
    }

    def __init__(self, probes=None, _configuration=None):  # noqa: E501
        """IperfSpeedProbes - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._probes = None
        self.discriminator = None

        self.probes = probes

    @property
    def probes(self):
        """Gets the probes of this IperfSpeedProbes.  # noqa: E501


        :return: The probes of this IperfSpeedProbes.  # noqa: E501
        :rtype: list[int]
        """
        return self._probes

    @probes.setter
    def probes(self, probes):
        """Sets the probes of this IperfSpeedProbes.


        :param probes: The probes of this IperfSpeedProbes.  # noqa: E501
        :type: list[int]
        """
        if self._configuration.client_side_validation and probes is None:
            raise ValueError("Invalid value for `probes`, must not be `None`")  # noqa: E501

        self._probes = probes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IperfSpeedProbes, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IperfSpeedProbes):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, IperfSpeedProbes):
            return True

        return self.to_dict() != other.to_dict()
