/*
 * Service API
 * Speedtest iperf service
 *
 * OpenAPI spec version: 0.1.0
 * Contact: dev@5gst.ru
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ru.fivegst.speedtest.client.service.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * IperfSpeedProbe
 */

public class IperfSpeedProbe {
  @SerializedName("bits_per_second")
  private Integer bitsPerSecond = null;

  public IperfSpeedProbe bitsPerSecond(Integer bitsPerSecond) {
    this.bitsPerSecond = bitsPerSecond;
    return this;
  }

   /**
   * Get bitsPerSecond
   * @return bitsPerSecond
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getBitsPerSecond() {
    return bitsPerSecond;
  }

  public void setBitsPerSecond(Integer bitsPerSecond) {
    this.bitsPerSecond = bitsPerSecond;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IperfSpeedProbe iperfSpeedProbe = (IperfSpeedProbe) o;
    return Objects.equals(this.bitsPerSecond, iperfSpeedProbe.bitsPerSecond);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bitsPerSecond);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IperfSpeedProbe {\n");
    
    sb.append("    bitsPerSecond: ").append(toIndentedString(bitsPerSecond)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

