swagger: '2.0'
info:
  title: Balancer API
  description: Speedtest load balancer
  contact:
    email: support@5gst.ru
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.1.0
host: 127.0.0.1:8000
schemes:
  - http
basePath: /Skoltech_OpenRAN_5G/iperf_load_balancer/0.1.0
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  Basic:
    type: basic
security:
  - Basic: []
paths:
  /service/:
    post:
      operationId: service_create
      description: Register caller as service
      parameters:
        - name: data
          in: body
          required: true
          schema:
            $ref: '#/definitions/ServerAddressRequest'
      responses:
        '201':
          description: Service registered
          schema:
            $ref: '#/definitions/ServerAddressRequest'
        '400':
          description: Invalid request body
      tags:
        - service
    delete:
      operationId: service_delete
      description: Unregister caller as service
      parameters:
        - name: data
          in: body
          required: true
          schema:
            $ref: '#/definitions/ServerAddressRequest'
      responses:
        '204':
          description: Service unregistered
          schema:
            $ref: '#/definitions/ServerAddressRequest'
        '400':
          description: Invalid request body
        '404':
          description: Service was not found
      tags:
        - service
    parameters: []
  /service/acquire/:
    post:
      operationId: service_acquire_create
      description: Acquires service for further iperf tests
      parameters: []
      responses:
        '200':
          description: Service acquired
          schema:
            $ref: '#/definitions/ServerAddressResponse'
        '503':
          description: No available services found
      tags:
        - service
    parameters: []
definitions:
  ServerAddressRequest:
    required:
      - ip
      - port
      - port_iperf
    type: object
    properties:
      ip:
        title: Ip
        type: string
        minLength: 1
      port:
        title: Port
        type: integer
        maximum: 65535
        minimum: 0
      port_iperf:
        title: Port iperf
        type: integer
        maximum: 65535
        minimum: 0
  ServerAddressResponse:
    required:
      - ip
      - port
      - port_iperf
      - time
    type: object
    properties:
      ip:
        title: Ip
        type: string
        minLength: 1
      port:
        title: Port
        type: integer
        maximum: 65535
        minimum: 0
      port_iperf:
        title: Port iperf
        type: integer
        maximum: 65535
        minimum: 0
      time:
        title: Time
        type: string
        format: date-time
