name: "[Balancer] Django tests"

on:
  push:
    paths:
      - 'balancer/**'
      - '.github/**'
  pull_request:
    paths:
      - 'balancer/**'
      - '.github/**'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: SECRET_KEY
      DEBUG: False
      SUPPORT_EMAIL: noreply@5gst.ru
    defaults:
      run:
        working-directory: ./balancer

    steps:
    - uses: actions/checkout@main
    - name: Install pip, pipenv and packages from Pipfile
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install
    - name: Run tests
      run: |
        pipenv run test
