name: "Run Balancer Tests"

on:
  workflow_call:

jobs:
  balancer-test:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: test
      TEST_MODE: "True"
    defaults:
      run:
        working-directory: ./balancer
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      # Work-around, see https://github.com/actions/checkout/issues/439
      - name: Update git repository
        run: git pull origin $(git rev-parse --abbrev-ref HEAD)

      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install pip, pipenv and packages from Pipfile
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev
      - name: Run tests
        run: |
          pipenv run test
