name: "Run Service Tests"

on: 
  workflow_call:

jobs:
  service-test:
    runs-on: ubuntu-latest
    env:
      SERVICE_IP_ADDRESS: localhost
      BALANCER_ADDRESS: localhost:5555
      IPERF_PORT: 5001
      SERVICE_PORT: 5000
      SECRET_KEY: test
    defaults:
      run:
        working-directory: ./service
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      # Work-around, see https://github.com/actions/checkout/issues/439
      - name: Update git repository
        run: git pull origin $(git rev-parse --abbrev-ref HEAD)

      - name: iPerf compilation
        run: ./scripts/build-iperf.sh

      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install pip, pipenv and packages from Pipfile
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev
      - name: Run tests
        run: |
          pipenv run test
            
