name: "[Service] Build docker image"

on: 
  push:
    branches: [main, develop]
    paths:
      - 'service/**'
      - '.github/**'
  pull_request:
    branches: [main, develop]
    paths:
      - 'service/**'
      - '.github/**'

jobs:
  build-iperf:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./service

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Compilation
        run: ./scripts/build-iperf.sh

      - name: Setup artifact content
        run: |
          mkdir gh-artifacts
          mv iPerf/src/iperf gh-artifacts/
          
          echo "artifactName=iperf-2.0.13.$GITHUB_RUN_NUMBER" > $GITHUB_ENV
      
      - name: Upload iperf binary to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.artifactName }}
          path: service/gh-artifacts/*

  speedtest-service:
    runs-on: ubuntu-20.04
    needs: build-iperf
    defaults:
      run:
        working-directory: ./service

    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/download-artifact@v2
        with:
          name: iperf-2.0.13.${{ github.run_number }}
          path: service
      
      - name: Setup artifact content
        run: |
          mkdir gh-artifacts/
          mv server.py gh-artifacts/
          mv iperf_wrapper.py gh-artifacts/
          mv iperf gh-artifacts/
          mv Dockerfile gh-artifacts/
          mv requirements.txt gh-artifacts/
          
          echo "artifactName=speedtest-service-$(cat VERSION).$GITHUB_RUN_NUMBER" > $GITHUB_ENV
      
      - name: Upload all server files to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.artifactName }}
          path: service/gh-artifacts/*

  publish-to-dockerhub:
    runs-on: ubuntu-20.04
    needs: speedtest-service
    defaults:
      run:
        working-directory: ./service
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup version variable
        run: echo "version=$(cat VERSION)" > $GITHUB_ENV
    
      - uses: actions/download-artifact@v2
        with:
          name: speedtest-service-${{ env.version }}.${{ github.run_number }}
          path: service/gh-artifacts

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./service/gh-artifacts
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/speedtest-service:${{ env.version }}

 
