name: Swagger code generator

on: [push]

jobs:
  generate:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@main    
    - name: save_controllers
      run: cp server/swagger_server/controllers/*_controller.py . # save our implementation for later use
    - name: Swagger Codegen v3
      uses: ducksify/swagger-codegen-action@v3.0
      with:
        args: >
          generate 
          -i server/swagger_server/swagger/swagger.yaml 
          -l python-flask 
          -o server
    - name: restore controllers
      run: |
        echo saving generated controllers to controllers_new
        for filename in server/swagger_server/controllers/*_controller.py; # renaming file
        do
        mv "$filename" "$(echo "$filename" | sed s/_controller.py/_controller_template.py/)";
        done

        echo restoring controllers
        cp *_controller.py server/swagger_server/controllers/
        rm *_controller.py
        echo replacing dateutil version 
        sed -i 's/python_dateutil == 2.6.0/python_dateutil == 2.7.0/' server/requirements.txt # replace dateutil version. Error with UTP on 2.6.0
        sed -i 's/flask_testing==0.8.0/flask_testing==0.8.1/' server/test-requirements.txt 
        sed -i 's/envlist = py35/envlist = py36/' server/tox.ini
    - uses: stefanzweifel/git-auto-commit-action@v4 # commiting changes
