name: Python tox tests

on: [push]

jobs:
  test:
   runs-on: ubuntu-latest
   strategy:
     matrix:
      python-version: [3.6]
   steps:
    - uses: actions/checkout@main
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.python-version}}
    - name: Install tox
      run: |
        python -m pip install --upgrade pip
        pip install tox 
    - name: fix flask version
      run: sed -i 's/flask_testing==0.8.0/flask_testing==0.8.1/' server/test-requirements.txt 
    - name: set tox version
      run: sed -i 's/envlist = py35/envlist = py36/' server/tox.ini
    - name: run tox
      run: |
        cd server
        tox
